create table draft_versions (
  id text primary key,
  draft_id text not null references drafts(id),
  version_number integer not null check (version_number >= 1),
  object_key text not null unique,
  content_hash text not null,
  file_size integer not null check (file_size >= 0),
  created_at text not null,
  updated_at text not null,
  created_by_api_key_id text not null references api_keys(id),
  source_ip text,
  user_agent text,
  cli_version text,
  git_branch text,
  git_commit_sha text,
  git_commit_subject text,
  git_dirty integer check (git_dirty in (0, 1) or git_dirty is null),
  original_filename text,
  request_id text,
  has_inline_script integer not null default 0 check (has_inline_script in (0, 1)),
  external_image_hosts text not null default '[]',
  ci_run_url text,
  ci_actor text,
  unique (draft_id, version_number)
);
